---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [44]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')

df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        13     0       0       2      2         0       0   
Algeria            12     5       2       8     15         3       0   
Argentina          23    18      24      28     70        18       0   
Armenia             5     1       2       9     12         6       0   
Australasia         2     3       4       5     12         0       0   

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Afghanistan         0         0        0       13       0         0         2   
Algeria             0         0        0       15       5         2         8   
Argentina           0         0        0       41      18        24        28   
Armenia             0         0        0       11       1         2         9   
Australasia         0         0        0        2       3         4         5   

             Combined total   ID  
Afghanistan               2  AFG  
Algeria                  15  ALG  
Argentina                70  ARG  
Armenia                  12  ARM  
Australasia              12  ANZ

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [45]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero() 

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [62]:
a = df['Gold'].max()
a

976

In [63]:
df[df['Gold']==a]

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
United States        26   976     757     666   2399        22      96   

               Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  \
United States       102        84      282       48    1072       859   

               Bronze.2  Combined total   ID  
United States       750            2681  USA

In [64]:
df[df['Gold']==a].index[0]

'United States'

In [65]:
def answer_one():
    a = df['Gold'].max()
    
    return df[df['Gold']==a].index[0]

In [66]:
answer_one()

'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [67]:
new = df.copy()
new['diff'] = new['Gold']-new['Gold.1']
new.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        13     0       0       2      2         0       0   
Algeria            12     5       2       8     15         3       0   
Argentina          23    18      24      28     70        18       0   
Armenia             5     1       2       9     12         6       0   
Australasia         2     3       4       5     12         0       0   

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Afghanistan         0         0        0       13       0         0         2   
Algeria             0         0        0       15       5         2         8   
Argentina           0         0        0       41      18        24        28   
Armenia             0         0        0       11       1         2         9   
Australasia         0         0        0        2       3         4         5   

             Combined total   ID  diff  
Afghanistan               2  AFG     0  
Algeria                  15  ALG     5  
Argentina                70  ARG    18  
Armenia                  12  ARM     1  
Australasia              12  ANZ     3

In [69]:
a = new['diff'].max()
a

880

In [70]:
new[new['diff'] == a].index[0]

'United States'

In [71]:
def answer_two():
    new = df.copy()
    new['diff'] = new['Gold']-new['Gold.1']
    a = new['diff'].max()
    
    return new[new['diff'] == a].index[0]

In [72]:
answer_two()

'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [88]:
new = df.copy()
new = new[(new['Gold.1']>0) & (new['Gold.2']>0)]
new.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  Silver.1  \
Australia        25   139     152     177    468        18       5         3   
Austria          26    18      33      35     86        22      59        78   
Belarus           5    12      24      39     75         6       6         4   
Belgium          25    37      52      53    142        20       1         1   
Bulgaria         19    51      85      78    214        19       1         2   

           Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Australia         4       12       43     144       155       181   
Austria          81      218       48      77       111       116   
Belarus           5       15       11      18        28        44   
Belgium           3        5       45      38        53        56   
Bulgaria          3        6       38      52        87        81   

           Combined total   ID  
Australia             480  AUS  
Austria               304  AUT  
Belarus                90  BLR  
Belgium               147  BEL  
Bulgaria              220  BUL

In [89]:
new['diff'] = new['Gold']-new['Gold.1']
new['relative'] = new['diff']/new['Gold.2']
new.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  Silver.1  \
Australia        25   139     152     177    468        18       5         3   
Austria          26    18      33      35     86        22      59        78   
Belarus           5    12      24      39     75         6       6         4   
Belgium          25    37      52      53    142        20       1         1   
Bulgaria         19    51      85      78    214        19       1         2   

           Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Australia         4       12       43     144       155       181   
Austria          81      218       48      77       111       116   
Belarus           5       15       11      18        28        44   
Belgium           3        5       45      38        53        56   
Bulgaria          3        6       38      52        87        81   

           Combined total   ID  diff  relative  
Australia             480  AUS   134  0.930556  
Austria               304  AUT   -41 -0.532468  
Belarus                90  BLR     6  0.333333  
Belgium               147  BEL    36  0.947368  
Bulgaria              220  BUL    50  0.961538

In [90]:
a = new['relative'].max()
a

0.96153846153846156

In [91]:
new[new['relative'] == a].index[0]

'Bulgaria'

In [94]:
def answer_three():
    new = df.copy()
    new = new[(new['Gold.1']>0) & (new['Gold.2']>0)]
    
    new['diff'] = new['Gold']-new['Gold.1']
    new['relative'] = new['diff']/new['Gold.2']
    a = new['relative'].max()
    
    return new[new['relative'] == a].index[0]

In [95]:
answer_three()

'Bulgaria'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [96]:
df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        13     0       0       2      2         0       0   
Algeria            12     5       2       8     15         3       0   
Argentina          23    18      24      28     70        18       0   
Armenia             5     1       2       9     12         6       0   
Australasia         2     3       4       5     12         0       0   

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Afghanistan         0         0        0       13       0         0         2   
Algeria             0         0        0       15       5         2         8   
Argentina           0         0        0       41      18        24        28   
Armenia             0         0        0       11       1         2         9   
Australasia         0         0        0        2       3         4         5   

             Combined total   ID  
Afghanistan               2  AFG  
Algeria                  15  ALG  
Argentina                70  ARG  
Armenia                  12  ARM  
Australasia              12  ANZ

In [100]:
points = pd.Series(df['Gold.2']*3 + df['Silver.2']*2 + df['Bronze.2']*1)
points.head()

Afghanistan      2
Algeria         27
Argentina      130
Armenia         16
Australasia     22
dtype: int64

In [101]:
points.shape

(146,)

In [103]:
def answer_four():
    points = pd.Series(df['Gold.2']*3 + df['Silver.2']*2 + df['Bronze.2']*1)

    return points

In [104]:
answer_four

<function __main__.answer_four>

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [152]:
census_df = pd.read_csv('census.csv')
census_df.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
0        4779736            4780127          4785161     ...        
1          54571              54571            54660     ...        
2         182265             182265           183193     ...        
3          27457              27457            27341     ...        
4          22915              22919            22861     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0          0.002295         -0.193196          0.381066          0.582002   
1          7.242091         -2.915927         -3.012349          2.265971   
2         14.832960         17.647293         21.845705         19.243287   
3         -4.728132         -2.500690         -7.056824         -3.904217   
4         -5.527043         -5.068871         -6.201001         -0.177537   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0         -0.467369     1.030015     0.826644     1.383282     1.724718   
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2         17.197872    15.844176    18.559627    22.727626    20.317142   
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533   

   RNETMIG2015  
0     0.712594  
1    -2.187333  
2    18.293499  
3   -10.543299  
4     1.107861  

[5 rows x 100 columns]

In [124]:
#State name
census_df[census_df['SUMLEV']==40].head()

SUMLEV  REGION  DIVISION  STATE  COUNTY      STNAME     CTYNAME  \
0        40       3         6      1       0     Alabama     Alabama   
68       40       4         9      2       0      Alaska      Alaska   
98       40       4         8      4       0     Arizona     Arizona   
114      40       3         7      5       0    Arkansas    Arkansas   
190      40       4         9      6       0  California  California   

     CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
0          4779736            4780127          4785161     ...        
68          710231             710249           714021     ...        
98         6392017            6392307          6408208     ...        
114        2915918            2915958          2922394     ...        
190       37253956           37254503         37334079     ...        

     RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0            0.002295         -0.193196          0.381066          0.582002   
68          -1.173489         -1.946424         -3.915107        -14.438910   
98           1.327489          5.245740          3.905473          6.219955   
114          1.365312         -0.432402         -0.442153         -1.060966   
190         -1.148464         -1.163788         -1.339869         -0.862856   

     RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0           -0.467369     1.030015     0.826644     1.383282     1.724718   
68         -10.407475     0.931274     1.818497    -0.757148   -11.271709   
98           6.776501     3.290378     7.337279     6.123606     8.761352   
114         -0.407735     2.326251     0.646395     0.682189     0.226168   
190         -1.981572     2.761704     2.647127     2.728645     3.743342   

     RNETMIG2015  
0       0.712594  
68     -6.881838  
98      9.335208  
114     0.901928  
190     2.656065  

[5 rows x 100 columns]

In [125]:
county = census_df[census_df['SUMLEV']==50]
county.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   
5      50       3         6      1       9  Alabama   Blount County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
1          54571              54571            54660     ...        
2         182265             182265           183193     ...        
3          27457              27457            27341     ...        
4          22915              22919            22861     ...        
5          57322              57322            57373     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
1          7.242091         -2.915927         -3.012349          2.265971   
2         14.832960         17.647293         21.845705         19.243287   
3         -4.728132         -2.500690         -7.056824         -3.904217   
4         -5.527043         -5.068871         -6.201001         -0.177537   
5          1.807375         -1.177622         -1.748766         -2.062535   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2         17.197872    15.844176    18.559627    22.727626    20.317142   
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533   
5         -1.369970     1.859511    -0.848580    -1.402476    -1.577232   

   RNETMIG2015  
1    -2.187333  
2    18.293499  
3   -10.543299  
4     1.107861  
5    -0.884411  

[5 rows x 100 columns]

In [126]:
county.groupby('STNAME').count()['CTYNAME']

STNAME
Alabama                  67
Alaska                   29
Arizona                  15
Arkansas                 75
California               58
Colorado                 64
Connecticut               8
Delaware                  3
District of Columbia      1
Florida                  67
Georgia                 159
Hawaii                    5
Idaho                    44
Illinois                102
Indiana                  92
Iowa                     99
Kansas                  105
Kentucky                120
Louisiana                64
Maine                    16
Maryland                 24
Massachusetts            14
Michigan                 83
Minnesota                87
Mississippi              82
Missouri                115
Montana                  56
Nebraska                 93
Nevada                   17
New Hampshire            10
New Jersey               21
New Mexico               33
New York                 62
North Carolina          100
North Dakota             53
Ohio         

In [127]:
county.groupby('STNAME').count()['CTYNAME'].idxmax()

'Texas'

In [128]:
def answer_five():
    county = census_df[census_df['SUMLEV']==50]

    return county.groupby('STNAME').count()['CTYNAME'].idxmax()

In [129]:
answer_five()

'Texas'

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [130]:
county = census_df[census_df['SUMLEV']==50]
county.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   
5      50       3         6      1       9  Alabama   Blount County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
1          54571              54571            54660     ...        
2         182265             182265           183193     ...        
3          27457              27457            27341     ...        
4          22915              22919            22861     ...        
5          57322              57322            57373     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
1          7.242091         -2.915927         -3.012349          2.265971   
2         14.832960         17.647293         21.845705         19.243287   
3         -4.728132         -2.500690         -7.056824         -3.904217   
4         -5.527043         -5.068871         -6.201001         -0.177537   
5          1.807375         -1.177622         -1.748766         -2.062535   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2         17.197872    15.844176    18.559627    22.727626    20.317142   
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533   
5         -1.369970     1.859511    -0.848580    -1.402476    -1.577232   

   RNETMIG2015  
1    -2.187333  
2    18.293499  
3   -10.543299  
4     1.107861  
5    -0.884411  

[5 rows x 100 columns]

In [132]:
county.sort_values(by = 'CENSUS2010POP', ascending = False)

SUMLEV  REGION  DIVISION  STATE  COUNTY         STNAME  \
209       50       4         9      6      37     California   
624       50       2         3     17      31       Illinois   
2667      50       3         7     48     201          Texas   
106       50       4         8      4      13        Arizona   
227       50       4         9      6      73     California   
220       50       4         9      6      59     California   
1884      50       1         2     36      47       New York   
372       50       3         5     12      86        Florida   
2623      50       3         7     48     113          Texas   
1901      50       1         2     36      81       New York   
223       50       4         9      6      65     California   
226       50       4         9      6      71     California   
1777      50       4         8     32       3         Nevada   
3017      50       4         9     53      33     Washington   
1335      50       2         3     26     163       Michigan   
2786      50       3         7     48     439          Texas   
233       50       4         9      6      85     California   
335       50       3         5     12      11        Florida   
2581      50       3         7     48      29          Texas   
1891      50       1         2     36      61       New York   
2333      50       1         2     42     101   Pennsylvania   
191       50       4         9      6       1     California   
1247      50       1         1     25      17  Massachusetts   
1912      50       1         2     36     103       New York   
224       50       4         9      6      67     California   
1863      50       1         2     36       5       New York   
1890      50       1         2     36      59       New York   
379       50       3         5     12      99        Florida   
2096      50       2         3     39      35           Ohio   
357       50       3         5     12      57        Florida   
...      ...     ...       ...    ...     ...            ...   
2763      50       3         7     48     393          Texas   
1643      50       4         8     30      37        Montana   
277       50       4         8      8      53       Colorado   
1733      50       2         4     31     103       Nebraska   
1773      50       2         4     31     183       Nebraska   
2698      50       3         7     48     263          Texas   
2028      50       2         4     38       7   North Dakota   
1780      50       4         8     32       9         Nevada   
1738      50       2         4     31     113       Nebraska   
1727      50       2         4     31      91       Nebraska   
2068      50       2         4     38      87   North Dakota   
1676      50       4         8     30     103        Montana   
290       50       4         8      8      79       Colorado   
2722      50       3         7     48     311          Texas   
306       50       4         8      8     111       Colorado   
1838      50       4         8     35      21     New Mexico   
1685      50       2         4     31       7       Nebraska   
96        50       4         9      2     282         Alaska   
1767      50       2         4     31     171       Nebraska   
2583      50       3         7     48      33          Texas   
1739      50       2         4     31     115       Nebraska   
1719      50       2         4     31      75       Nebraska   
1740      50       2         4     31     117       Nebraska   
1659      50       4         8     30      69        Montana   
1686      50       2         4     31       9       Nebraska   
1684      50       2         4     31       5       Nebraska   
2697      50       3         7     48     261          Texas   
2701      50       3         7     48     269          Texas   
560       50       4         9     15       5         Hawaii   
2717      50       3         7     48     301          Texas   

                       CTYNAME  CENSU

In [134]:
new = county.sort_values(by = 'CENSUS2010POP', ascending = False).groupby('STNAME').head(3)
new

SUMLEV  REGION  DIVISION  STATE  COUNTY         STNAME  \
209       50       4         9      6      37     California   
624       50       2         3     17      31       Illinois   
2667      50       3         7     48     201          Texas   
106       50       4         8      4      13        Arizona   
227       50       4         9      6      73     California   
220       50       4         9      6      59     California   
1884      50       1         2     36      47       New York   
372       50       3         5     12      86        Florida   
2623      50       3         7     48     113          Texas   
1901      50       1         2     36      81       New York   
1777      50       4         8     32       3         Nevada   
3017      50       4         9     53      33     Washington   
1335      50       2         3     26     163       Michigan   
2786      50       3         7     48     439          Texas   
335       50       3         5     12      11        Florida   
1891      50       1         2     36      61       New York   
2333      50       1         2     42     101   Pennsylvania   
1247      50       1         1     25      17  Massachusetts   
379       50       3         5     12      99        Florida   
2096      50       2         3     39      35           Ohio   
2284      50       1         2     42       3   Pennsylvania   
1316      50       2         3     26     125       Michigan   
2103      50       2         3     39      49           Ohio   
1364      50       2         4     27      53      Minnesota   
2895      50       3         5     51      59       Virginia   
2839      50       4         8     49      35           Utah   
1604      50       2         4     29     189       Missouri   
109       50       4         8      4      19        Arizona   
1228      50       3         5     24      31       Maryland   
559       50       4         9     15       3         Hawaii   
...      ...     ...       ...    ...     ...            ...   
886       50       2         4     19     163           Iowa   
324       50       3         5     10       1       Delaware   
1442      50       3         6     28      33    Mississippi   
1069      50       3         6     21     117       Kentucky   
1758      50       2         4     31     153       Nebraska   
2855      50       1         1     50       7        Vermont   
562       50       4         9     15       9         Hawaii   
1206      50       1         1     23      19          Maine   
2033      50       2         4     38      17   North Dakota   
1680      50       4         8     30     111        Montana   
1800      50       1         1     33      13  New Hampshire   
1853      50       4         8     35      49     New Mexico   
591       50       4         8     16      55          Idaho   
2355      50       1         1     44       9   Rhode Island   
1656      50       4         8     30      63        Montana   
3042      50       3         5     54       3  West Virginia   
2455      50       2         4     46     103   South Dakota   
76        50       4         9      2      90         Alaska   
3046      50       3         5     54      11  West Virginia   
3180      50       4         8     56      21        Wyoming   
1639      50       4         8     30      29        Montana   
85        50       4         9      2     170         Alaska   
2032      50       2         4     38      15   North Dakota   
3182      50       4         8     56      25        Wyoming   
2042      50       2         4     38      35   North Dakota   
2862      50       1         1     50      21        Vermont   
2863      50       1         1     50      23        Vermont   
1792      50       4         8     32     510         Nevada   
3172      50       4         8     56       5        Wyoming   
2444      50       2         4     46      83   South Dakota   

                           CTYNAME  C

In [135]:
new.groupby('STNAME').sum().sort_values('CENSUS2010POP', ascending = False)

SUMLEV  REGION  DIVISION  STATE  COUNTY  CENSUS2010POP  \
STNAME                                                                         
California               150      12        27     18     169       15924150   
Texas                    150       9        21    144     753        8269632   
Illinois                 150       6         9     51     171        6815061   
New York                 150       3         6    108     189        6321295   
Florida                  150       9        15     36     196        5564635   
Arizona                  150      12        24     12      53        5173150   
Michigan                 150       6         9     78     387        3863924   
Pennsylvania             150       3         6    126     195        3549228   
Washington               150      12        27    159     147        3439809   
Ohio                     150       6         9    117     145        3245910   
Massachusetts            150       3         3     75      53        3044796   
Connecticut              150       3         3     27      13        2673320   
Maryland                 150       9        15     72      69        2640226   
New Jersey               150       3         6    102      39        2498943   
Nevada                   150      12        24     96     544        2427950   
Georgia                  150       9        15     39     345        2417795   
North Carolina           150       9        15    111     383        2309027   
Minnesota                150       6        12     81     213        2059617   
Missouri                 150       6        12     87     467        2033597   
Tennessee                150       9        18    141     287        1986551   
Virginia                 150       9        15    153    1022        1921722   
Utah                     150      12        24    147      95        1852698   
Wisconsin                150       6         9    165     237        1825699   
Colorado                 150      12        24     24      77        1794424   
Indiana                  150       6         9     54     189        1754727   
Oregon                   150      12        27    123     123        1641036   
Oklahoma                 150       9        21    120     279        1577791   
Alabama                  150       9        18      3     259        1406269   
Hawaii                   150      12        27     45      13        1293120   
Kansas                   150       6        12     60     441        1220478   
Louisiana                150       9        21     66     155        1216552   
Kentucky                 150       9        18     63     295        1196619   
South Carolina           150       9        15    135     143        1185938   
New Mexico               150      12        24    105      63        1015967   
Nebraska                 150       6        12     93     317         961357   
Rhode Island             150       3         3    132      19         919804   
Delaware                 150       9        15     30       9         897934   
New Hampshire            150       3         3     99      39         842389   
Arkansas                 150       9        21     15     269         807152   
Iowa                     150       6        12     57     429         807090   
Idaho                    150      12        24     48      83         719782   
Maine                    150       3         3     69      55         632728   
District of Columbia      50       3         5     11       1         601723   
Mississippi              150       9        18     84     129         593642   
Alaska                   150      12        27      6     280         478402   
West Virginia            150       9        15    162      53         393551   
Montana                  150      12        24     90     203         348199   
South Dakota             150       6        12    138     285         315244   
North Dakota          

In [138]:
new.groupby('STNAME').sum().sort_values('CENSUS2010POP', ascending = False).head(3).index.tolist()

['California', 'Texas', 'Illinois']

In [139]:
def answer_six():
    county = census_df[census_df['SUMLEV']==50]
    new = county.sort_values(by = 'CENSUS2010POP', ascending = False).groupby('STNAME').head(3)
    
    return new.groupby('STNAME').sum().sort_values('CENSUS2010POP', ascending = False).head(3).index.tolist()

In [140]:
answer_six()

['California', 'Texas', 'Illinois']

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [153]:
census_df.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
0        4779736            4780127          4785161     ...        
1          54571              54571            54660     ...        
2         182265             182265           183193     ...        
3          27457              27457            27341     ...        
4          22915              22919            22861     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0          0.002295         -0.193196          0.381066          0.582002   
1          7.242091         -2.915927         -3.012349          2.265971   
2         14.832960         17.647293         21.845705         19.243287   
3         -4.728132         -2.500690         -7.056824         -3.904217   
4         -5.527043         -5.068871         -6.201001         -0.177537   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0         -0.467369     1.030015     0.826644     1.383282     1.724718   
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2         17.197872    15.844176    18.559627    22.727626    20.317142   
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533   

   RNETMIG2015  
0     0.712594  
1    -2.187333  
2    18.293499  
3   -10.543299  
4     1.107861  

[5 rows x 100 columns]

In [154]:
census_df[census_df['SUMLEV']==50].shape

(3142, 100)

In [155]:
census_df.shape

(3193, 100)

In [156]:
county = census_df[census_df['SUMLEV']==50]
columns = ['POPESTIMATE2010',
                   'POPESTIMATE2011',
                   'POPESTIMATE2012',
                   'POPESTIMATE2013',
                   'POPESTIMATE2014',
                   'POPESTIMATE2015']

In [160]:
max_value = county[columns].max(axis = 0)
max_value

POPESTIMATE2010     9826009
POPESTIMATE2011     9896602
POPESTIMATE2012     9970436
POPESTIMATE2013    10045175
POPESTIMATE2014    10109436
POPESTIMATE2015    10170292
dtype: int64

In [165]:
max_value = county[columns].max(axis = 1)
max_value

1        55347
2       203709
3        27341
4        22861
5        57776
6        10887
7        20944
8       118437
9        34153
10       26084
11       43943
12       13841
13       25767
14       13880
15       15072
16       51211
17       54514
18       13208
19       11758
20       38060
21       13963
22       82005
23       50358
24       43803
25       71387
26       81468
27       38309
28      104442
29       17231
30       31734
         ...  
3162     15930
3163    133674
3164    396488
3165     52422
3166     24581
3167    169639
3168     74807
3170     37956
3171     12022
3172     49220
3173     15856
3174     14343
3175      7444
3176     41129
3177     13666
3178      4846
3179      8636
3180     97121
3181     18722
3182     82178
3183      2548
3184     29237
3185      8812
3186     30020
3187     10418
3188     45162
3189     23125
3190     21102
3191      8545
3192      7234
dtype: int64

In [166]:
min_value = county[columns].min(axis = 1)
min_value

1        54660
2       183193
3        26489
4        22512
5        57373
6        10606
7        20154
8       115620
9        33993
10       25859
11       43665
12       13170
13       24675
14       13456
15       14921
16       50177
17       54354
18       12662
19       10724
20       37796
21       13853
22       80374
23       49501
24       41131
25       70869
26       79465
27       37784
28      103057
29       16759
30       31507
         ...  
3162     15552
3163    131967
3164    390076
3165     51945
3166     24033
3167    167059
3168     73435
3170     36428
3171     11672
3172     46244
3173     15559
3174     13728
3175      7114
3176     40222
3177     13383
3178      4741
3179      8552
3180     92271
3181     17943
3182     75472
3183      2475
3184     28259
3185      8678
3186     29146
3187      9899
3188     43593
3189     21297
3190     20822
3191      8316
3192      7065
dtype: int64

In [167]:
diff = max_value - min_value
county['diff'] = diff
county['diff'].idxmax()

2667

In [170]:
def answer_seven():
    county = census_df[census_df['SUMLEV'] == 50]
    county = county.set_index('CTYNAME')
    columns = ['POPESTIMATE2010',
                   'POPESTIMATE2011',
                   'POPESTIMATE2012',
                   'POPESTIMATE2013',
                   'POPESTIMATE2014',
                   'POPESTIMATE2015']
#     print(counties_df[columns])
    max_value = county[columns].max(axis = 1)
    min_value = county[columns].min(axis = 1)
    diff = max_value - min_value
    county['diff'] = diff
    
    return county['diff'].idxmax()
    

In [171]:
answer_seven()

'Harris County'

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [175]:
county = census_df[census_df['SUMLEV'] == 50]
county[((county['REGION'] == 1) | (county['REGION'] == 2)) 
            & (county['CTYNAME'] == 'Washington County') 
            & (county['POPESTIMATE2015'] > county['POPESTIMATE2014'])][['STNAME','CTYNAME']]

STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County

In [176]:
def answer_eight():
    county = census_df[census_df['SUMLEV'] == 50]
    a = county[((county['REGION'] == 1) | (county['REGION'] == 2)) 
            & (county['CTYNAME'] == 'Washington County') 
            & (county['POPESTIMATE2015'] > county['POPESTIMATE2014'])][['STNAME','CTYNAME']]
    return a

In [177]:
answer_eight()

STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County